name: BiSM
channels:
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.4
  - torchvision=0.5
  - tensorboard=2.1
  - matplotlib=3.1
  - seaborn=0.9
  - scikit-learn=0.21
  - tqdm=4.36
  - pip:
    - higher==0.2
