name: "latent_ebm_resnet_cifar10_bimdsm"
include: "latent_ebm_resnet_cifar10.yml"
criterion:
  family: "BiMDSM"
loss:
  inner_loss_type: "cond_fisher"
  sigma_begin: 0.05
  sigma_end: 1.2
  dist: "linear"
  sigma0: 0.1  # fix
update:
  n_unroll: 0
  n_inner_loops: 5
others:
  sample_method: "via_q"
