name: "grbm_toy_bissm"
include: "grbm_toy.yml"
criterion:
  family: "BiSSM"
loss:
  inner_loss_type: "iwae"
  k: 1
update:
  n_unroll: 5
  n_inner_loops: 5
q:
  family: "LinearBernoulliQ"
  temperature: 0.1
